version: '3.9'

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    env_file: ./.env
    ports: 
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine3.15
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5431:5432

volumes:
  postgres_data:
